const constants = {
    AUTHOR_CREATE_START : "AUTHOR_CREATE_START",
    AUTHOR_CREATE_SUCCESS : "AUTHOR_CREATE_SUCCESS",
    AUTHOR_CREATE_ERROR : "AUTHOR_CREATE_ERROR",

    AUTHOR_GET_START : "AUTHOR_GET_START",
    AUTHOR_GET_SUCCESS : "AUTHOR_GET_SUCCESS",
    AUTHOR_GET_ERROR : "AUTHOR_GET_ERROR",

    AUTHOR_UPDATE_START : "AUTHOR_UPDATE_START",
    AUTHOR_UPDATE_SUCCESS : "AUTHOR_UPDATE_SUCCESS",
    AUTHOR_UPDATE_ERROR : "AUTHOR_UPDATE_ERROR",

    AUTHOR_FIND_START : "AUTHOR_FIND_START",
    AUTHOR_FIND_SUCCESS : "AUTHOR_FIND_SUCCESS",
    AUTHOR_FIND_ERROR : "AUTHOR_FIND_ERROR",

    AUTHOR_DESTROY_START : "AUTHOR_DESTROY_START",
    AUTHOR_DESTROY_SUCCESS : "AUTHOR_DESTROY_SUCCESS",
    AUTHOR_DESTROY_ERROR : "AUTHOR_DESTROY_ERROR",

    AUTHOR_FORM_VALUE_CHANGE : "AUTHOR_FORM_VALUE_CHANGE",


    TOGGLE_MODAL: "TOGGLE_MODAL",
    AUTHOR_CLEAR_AUTHOR: "AUTHOR_CLEAR_AUTHOR"
};

export default constants;