const constants = {
    CATEGORY_CREATE_START : "CATEGORY_CREATE_START",
    CATEGORY_CREATE_SUCCESS : "CATEGORY_CREATE_SUCCESS",
    CATEGORY_CREATE_ERROR : "CATEGORY_CREATE_ERROR",

    CATEGORY_GET_START : "CATEGORY_GET_START",
    CATEGORY_GET_SUCCESS : "CATEGORY_GET_SUCCESS",
    CATEGORY_GET_ERROR : "CATEGORY_GET_ERROR",

    CATEGORY_UPDATE_START : "CATEGORY_UPDATE_START",
    CATEGORY_UPDATE_SUCCESS : "CATEGORY_UPDATE_SUCCESS",
    CATEGORY_UPDATE_ERROR : "CATEGORY_UPDATE_ERROR",

    CATEGORY_FIND_START : "CATEGORY_FIND_START",
    CATEGORY_FIND_SUCCESS : "CATEGORY_FIND_SUCCESS",
    CATEGORY_FIND_ERROR : "CATEGORY_FIND_ERROR",

    CATEGORY_DESTROY_START : "CATEGORY_DESTROY_START",
    CATEGORY_DESTROY_SUCCESS : "CATEGORY_DESTROY_SUCCESS",
    CATEGORY_DESTROY_ERROR : "CATEGORY_DESTROY_ERROR",

    CATEGORY_FORM_VALUE_CHANGE : "CATEGORY_FORM_VALUE_CHANGE",


    TOGGLE_MODAL: "TOGGLE_MODAL",
    CATEGORY_CLEAR_CATEGORY: "CATEGORY_CLEAR_CATEGORY"
};

export default constants;