const constants = {
    PUBLISHER_CREATE_START : "PUBLISHER_CREATE_START",
    PUBLISHER_CREATE_SUCCESS : "PUBLISHER_CREATE_SUCCESS",
    PUBLISHER_CREATE_ERROR : "PUBLISHER_CREATE_ERROR",

    PUBLISHER_GET_START : "PUBLISHER_GET_START",
    PUBLISHER_GET_SUCCESS : "PUBLISHER_GET_SUCCESS",
    PUBLISHER_GET_ERROR : "PUBLISHER_GET_ERROR",

    PUBLISHER_UPDATE_START : "PUBLISHER_UPDATE_START",
    PUBLISHER_UPDATE_SUCCESS : "PUBLISHER_UPDATE_SUCCESS",
    PUBLISHER_UPDATE_ERROR : "PUBLISHER_UPDATE_ERROR",

    PUBLISHER_FIND_START : "PUBLISHER_FIND_START",
    PUBLISHER_FIND_SUCCESS : "PUBLISHER_FIND_SUCCESS",
    PUBLISHER_FIND_ERROR : "PUBLISHER_FIND_ERROR",

    PUBLISHER_DESTROY_START : "PUBLISHER_DESTROY_START",
    PUBLISHER_DESTROY_SUCCESS : "PUBLISHER_DESTROY_SUCCESS",
    PUBLISHER_DESTROY_ERROR : "PUBLISHER_DESTROY_ERROR"
};

export default constants;