const constants = {
    BOOK_CREATE_START : "BOOK_CREATE_START",
    BOOK_CREATE_SUCCESS : "BOOK_CREATE_SUCCESS",
    BOOK_CREATE_ERROR : "BOOK_CREATE_ERROR",

    BOOK_GET_START : "BOOK_GET_START",
    BOOK_GET_SUCCESS : "BOOK_GET_SUCCESS",
    BOOK_GET_ERROR : "BOOK_GET_ERROR",

    BOOK_UPDATE_START : "BOOK_UPDATE_START",
    BOOK_UPDATE_SUCCESS : "BOOK_UPDATE_SUCCESS",
    BOOK_UPDATE_ERROR : "BOOK_UPDATE_ERROR",

    BOOK_FIND_START : "BOOK_FIND_START",
    BOOK_FIND_SUCCESS : "BOOK_FIND_SUCCESS",
    BOOK_FIND_ERROR : "BOOK_FIND_ERROR",

    BOOK_DESTROY_START : "BOOK_DESTROY_START",
    BOOK_DESTROY_SUCCESS : "BOOK_DESTROY_SUCCESS",
    BOOK_DESTROY_ERROR : "BOOK_DESTROY_ERROR",

    BOOK_PHOTO_DESTROY_START: "BOOK_PHOTO_DESTROY_START",
    BOOK_PHOTO_DESTROY_SUCCESS: "BOOK_PHOTO_DESTROY_SUCCESS",
    BOOK_PHOTO_DESTROY_ERROR: "BOOK_PHOTO_DESTROY_ERROR",

    BOOK_FORM_VALUE_CHANGE : "BOOK_FORM_VALUE_CHANGE",

    TOGGLE_MODAL: "TOGGLE_MODAL",
    BOOK_CLEAR_BOOK: "BOOK_CLEAR_BOOK"
};

export default constants;